[package]
name = "graph"
version = "0.0.1"
edition = "2021"

[lib]
name = "graph"
path = "src/main/rust/lib.rs"

[dependencies]
env_logger = "0.9"
log = "0.4"
serde = { version = "1.0", features = ["derive", "rc"]}
thiserror = "1.0"

[dev-dependencies]
serde_json = "1.0"

